### ISSUE TITLE
Touch screen does not mean mobile browser

### ISSUE THREAD

**Issue by Jackbennett** [s-a/TRY.js#1]
Hey, a part of `lib/try/engine.js:1025` leaves up a "desktop only" splash screen.

`lib/try/gui.js` creates window.isMobile if the 'ontouchstart' function is present. 

My 13" touchscreen i7 laptop is nice but it's no mobile device. I think this isn't the right kind of browser feature detection you want. 

Your site doesn't work on anything with a touchscreen I assume, which include quite a few hi-spec laptops.

**Comment by s-a** [comment]
You are right. Unfortunately there does not exist a secure way to detect a mouse input presence on devices. So far even Modernizr does not know how. https://github.com/Modernizr/Modernizr/issues/869. I added a link `But I want to use it anyway.` to load the app regardless of whether you are on a touch device to work around this issue.
